# Generated by Django 5.1.2 on 2024-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vectorstore',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
