# Generated by Django 5.1.2 on 2024-10-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_vectorstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vectorstore',
        ),
        migrations.AddField(
            model_name='document',
            name='vectorstore_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
