# Generated by Django 5.1.2 on 2024-10-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vectorstore_data',
        ),
    ]
