# Generated by Django 5.1.2 on 2024-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_vectorstore_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vectorstore_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
