# Generated by Django 5.1.2 on 2024-10-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_vectorstore_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('txt', 'Text'), ('md', 'Markdown')], max_length=10, null=True),
        ),
    ]
